model_api:
  base_url: https://example.com/v1
  api_key: secret

snowflake:
  user: username
  password: python-token
  account: RSRSBDK-YDB67606
  role: PARTICIPANT
  warehouse: COMPUTE_WH_PARTICIPANT
